### PR TITLE
honor showUntrackedFiles config

### LINKED ISSUE #752: Support using gitui with yadm
**Is your feature request related to a problem? Please describe.**
This is half a feature request and half a bug. 
I use YADM for managing my dotfiles, which essentially creates a bare git repo in the $HOME directory.
YADM adds a configuration option so when I do `yadm status` it doesnt try show all the untracked files.

https://git-scm.com/docs/git-status#Documentation/git-status.txt---untracked-filesltmodegt

On the other hand when I try to use gitui (using `gitui -d ~/.config/yadm/repo.git`), 
it gets stuck 'forever' probably trying to find/enumerate all the untracked files.
(Sublime Merge also seems to have this problem, but for example verco doesn't)

I suspect similar problems would happen in large repositories with large amounts of changed/untracked files

**Describe the solution you'd like**
I see a few ways this could be fixed

1. check for the status.showUntrackedFiles config option and dont spend time trying to list untracked files/directories
2. add a `no-untracked` flag to do something similar to above
3. detect when there are alot of untracked files and stop trying to find more than is visible in the window
   - find the rest on-demand
4. somehow make gitui still/more responsive while finding/rendering the untracked files anyway
5. ETA: there is also the `gui.displayuntracked` which is more directly related to GUIs and untracked files, it would be a good idea to look at this option too

**Describe alternatives you've considered**
Unfortunately gitui is not really usable with YADM

### PR DESCRIPTION
**Pull request by extrawurst**
closes #752

### CODE REVIEW

**Comment by IndianBoy42** [comment]
Should you check [gui.displayuntracked](https://git-cola.readthedocs.io/en/latest/git-cola.html#gui-displayuntracked)?

I can't seem to find if it's an official flag or only for git-cola. It is mentioned in the official git repo [here](https://github.com/git/git/blob/master/Documentation/config/gui.txt)

**Comment by extrawurst** [comment]
> Should you check [gui.displayuntracked](https://git-cola.readthedocs.io/en/latest/git-cola.html#gui-displayuntracked)?
> 
> I can't seem to find if it's an official flag or only for git-cola. It is mentioned in the official git repo [here](https://github.com/git/git/blob/master/Documentation/config/gui.txt)

I went for the more standard config

**Comment by IndianBoy42** [comment]
It partially works, it doesn't show the untracked files. However it still attempts to stage them when I run "Stage All"

I think either Stage-All should ignore untracked files (if `status.showUntrackedFiles == no`). Or we add a separate key for 'Update-All' which mimics `git add -u`

For example these commits in my fork:
1. https://github.com/IndianBoy42/gitui/commit/8ea8bfa49908c996dd520106e153e24ffdfda384
2. https://github.com/IndianBoy42/gitui/commit/4b2215abe9a01ab90a1a10d170ffab17d9b3b7ff

**Comment by IndianBoy42** [comment]
I have manually 'rebased' my fork onto your new  way of getting the `showUntrackedFiles` option

https://github.com/IndianBoy42/gitui

If you are okay with it I can send a pull request after this PR is merged

**Comment by extrawurst** [comment]
@IndianBoy42 I will fix the stage_all it should honour the same config. but an additional command for staging untracked files when you configured it to not show them does not carry its own weight IMO

**Comment by extrawurst** [comment]
@IndianBoy42 `stage_all` honors the config too now

**Comment by IndianBoy42** [comment]
This works well now.

Sorry to keep bothering but I remembered another thing that I added in my branch.

You may want the 'stash untracked' option to be unchecked by default if `showUntrackedFiles==no`. This is not a big deal because you can always unselect it before stashing, but its a little less error prone

**Comment by extrawurst** [comment]
> This works well now.
> 
> Sorry to keep bothering but I remembered another thing that I added in my branch.
> 
> You may want the 'stash untracked' option to be unchecked by default if `showUntrackedFiles==no`. This is not a big deal because you can always unselect it before stashing, but its a little less error prone

should work now

**Pull request merged**
