### PR TITLE
allow undefined user.name on commit

### LINKED ISSUE #79: The commit function does not work when you have user.email but no user.name defined
**Describe the bug**
In gitui v0.3.0 the commit function does not allow a commit to be made when the user has a user.email defined and no user.name defined.

It took me a while to discover that there is a difference between user.name being defined as empty (`git config user.name ""`) and it being undefined (as in, `git config --list` does not show the entry at all).

In the empty case, interestingly enough, git commit does not allow the commit to be made, likewise gitui does not allow it.

In the undefined case, git commit does allow the commit to be made (and I think it shows `unknown` in that field in later `git log` or `git show` calls). This is where the gitui behaviour is different, as gitui does not allow a commit to be made with this message:
```
 Status   |   Log
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌Unstaged Changes [1]──────┌Error──────────────────────────────────────────────────────────┐───────────────────────────┐
│                          │commit failed:                                                 │                           │
│                          │git error:config value 'user.name' was not found; class=Config │                           │
│                          │(7); code=NotFound (-3)                                        │                           │
│                          │                                                               │                           │
```

**Expected behavior**
gitui would allow a commit to be made and fill in `unknown` as git commit does.

### PR DESCRIPTION
**Pull request by mxork**
fixes #79

### CODE REVIEW

**Comment by extrawurst** [comment]
@mxork thanks for fixing this! 🥳

**Comment by extrawurst** [comment]
@mxork did you try coming up with a unites for this? I am struggling with this

**Comment by extrawurst** [comment]
@mxork I need to roll this back I think, it keeps failing for me and I am wondering how you managed to get `Config::get_str` to work at all: https://github.com/rust-lang/git2-rs/issues/474

**Comment by extrawurst** [comment]
@mxork see here for the failing CI: https://github.com/extrawurst/gitui/runs/816484457

**Comment by extrawurst** [comment]
@mxork I am sorry I had to revert this, but I should have checked it out more thorough in the first place. It would be awesome if you could update it using `get_entry` (or any other config method that works on non-snapshots unlike `get_str` [see docs](https://libgit2.org/libgit2/#HEAD/group/config/git_config_get_string)) and most importantly have a working unittest.

This seems to be one of those implementations where writing the test by far outweighs writing the feature itself 🙈

**Comment by mxork** [comment]
This absolutely should have had a big WIP on the front of it.

I'll try to figure out a test. Sorry you spent time chasing it around.

**Comment by extrawurst** [comment]
@mxork no worries! happy you wanna contribute. Feel free to join the discord to simplify discussion: https://discord.gg/7TGFfuq

**Pull request merged**
