### PR TITLE
Multi line

### PR DESCRIPTION
**Pull request by pm100**
This is the bare minimum (as requested) of changes to fix this bug https://github.com/extrawurst/gitui/issues/405

 - You can still edit the first line when you return from the external editor.
 -  If you backspace out the whole first line then the second line moves up tp become the first line. I can prevent that if you like.
 -  There is no way to see more lines than will fit in the dialog box

Its my understanding that this is what others wanted.

Note - the display of the hard unicode CR character is gone because I wasnt sure what to do with it. The current code only shows it on the current line (which can only be the first one), should it be shown on every line? In what place? Should it be added if it would make the line overflow the screen width

### CODE REVIEW

**Comment by pm100** [comment]
correct branch this time :-)

**Comment by pm100** [comment]
these failures are also clippy complaints about revlog.rs

**Comment by pm100** [comment]
reminder - I have another PR that converts the textinput dialog to full multi line capabilities (when in multi-line mode)

**Comment by WizardOhio24** [comment]
With this, it still has the previous fixes for the underline not being displayed, now covered in #404, you might want to revert that commit(680d3d2) so the rebase/merge when merging isn't difficult.

**Comment by pm100** [comment]
closing till other PR resolved

**Pull request closed without merging**
