### PR TITLE
make XDG_XXX_HOME work for Windows

### LINKED ISSUE #1498: Follow XDG spec on windows
**Is your feature request related to a problem? Please describe.**
I use windows and have set XDG_CONFIG dirs (XDG_CONFIG_HOME, XDG_CACHE_HOME) but gitui isn't honoring them

**Describe the solution you'd like**
If XDG_CONFIG_HOME is set on any os, use XDG_CONFIG_HOME/gitui as directory for config file.   If it is not set, fall back to os default

### PR DESCRIPTION
**Pull request by pm100**
This Pull Request fixes/closes #1498.

- If XDG_CONFIG_HOME is set on Windows then use it instead of what `dirs_next` says
- if XDG_CACHE_HOME is set on Windows then use it instead of what `dirs_next` says

Note that `dirs_next` already honors XDG_XXX_HOME on Linux

It is arguable that not doing this for Mac is odd, but that not whats asked for in the bug.

I followed the checklist:
- [ ] I added unittests
- [ x] I ran `make check` without errors
- [ x] I tested the overall application
- [ ] I added an appropriate item to the changelog

### CODE REVIEW

**Comment by extrawurst** [comment]
Can we try and be good citizens and file this upstream and try making it a PR there?

**Comment by pm100** [comment]
I am not sure what you are saying. 

Are you responding to my Macos comment, do you want me to add the same feature for Mac. In this PR? Or do you want a new issue for Mac to support XDG. In the past I got shot down here for doing more than was precisely asked in an issue.

Or did I do something wrong with this PR in terms of how it intersects with branches etc (I see the word 'upstream', which I am just now understanding). I am very limited in my git/github/PR experience and could have made a mistake.

**Comment by extrawurst** [comment]
I m saying if you think it should be a Feature of `dirs_next` let’s try to add it as a PR over there (upstream) first before, WDYT?

**Comment by pm100** [comment]
@extrawurst OK I understand.

No I dont thing that dirs_next should do it. Its a linux thing. Do what they do is fine.

Note that git explicitly describes the support of XDG, without qualifying it by platform. https://git-scm.com/docs/git-config#FILES. So we should too

I have verified that libgit2 obeys XDG cross platform. So in fact we do honor it. The code change I made makes it work for 2 things that we implement without libgit2, log file location and keyboard map location. And I do think we should do that for Mac too

However I am now surprised about the original issue. Its a blanket statement about not supporting XDG on windows (but with no mention of those 2 items, log and keyboard). I have asked the original poster to clarify, because maybe there is something else going on.

I am going to close this PR while awaiting the response. And I will add Mac support too

**Pull request closed without merging**
