### PR TITLE
Issue/876/merge branch closes window

### PR DESCRIPTION
**Pull request by andrewpollack**
This Pull Request fixes/closes #{876}.

It changes the following:
- Changed `merge_branch` function to take self as a mutable pointer.
- Added `self.hide();` between merging of branch and push to queue to update.

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [x] I added an appropriate item to the changelog

### CODE REVIEW

**Comment by extrawurst** [comment]
one round of general GitHub markdown feedback:

> This Pull Request fixes/closes #{876}.

if you remove the curly braces, it becomes a nicely clickable link

> * [N/A] I added unittests

just leaving it empty `[ ]` renders a nice unchecked checkbox

> * [ ✔️ ] I ran `make check` without errors

just making it `[x]` renders a checked checkbox.
please use the preview tab to check if you used the GitHub markdown correctly

**Comment by extrawurst** [comment]
@andrewpollack is this up to date with master? I cannot rebase-merge it

**Comment by andrewpollack** [comment]
> @andrewpollack is this up to date with master? I cannot rebase-merge it

Looks like a few commits merged in between PR and now -- I've updated and now it's up-to-date with master

**Comment by andrewpollack** [comment]
> one round of general GitHub markdown feedback:
> 
> > This Pull Request fixes/closes #{876}.
> 
> if you remove the curly braces, it becomes a nicely clickable link
> 
> > * [N/A] I added unittests
> 
> just leaving it empty `[ ]` renders a nice unchecked checkbox
> 
> > * [ heavy_check_mark ] I ran `make check` without errors
> 
> just making it `[x]` renders a checked checkbox.
> please use the preview tab to check if you used the GitHub markdown correctly

Thank you!! I edited the original with this feedback

**Pull request merged**
