### PR TITLE
FuzzyFindPopup for general use

### LINKED ISSUE #1660: Implement a generic fuzzy find popup
consolidate FileFindPopup and BranchFindPopup, as discussed in https://github.com/extrawurst/gitui/pull/1658#discussion_r1171291090

### PR DESCRIPTION
**Pull request by UUGTech**
This Pull Request closes #1660.

I implemented FuzzyFindPopup for general use.

When we want to add FuzzyFindPopup for something, we can add it by following steps.
- Add a variant of `FuzzyFinderTarget` (ex: `Braches`, `Files`)
- Add popup open command. Use `InternalEvent::OpenFuzzyFinder`, example of Branches is below. Need to pass contents (`Vec<String>`) and a variant of `FuzzyFinderTarget`.
```rust
				self.queue.push(InternalEvent::OpenFuzzyFinder(
					branches,
					FuzzyFinderTarget::Branches,
				));
```
- Add update process for change of fuzzy finder selection in `src/app.rs`. `idx` and `content` are available.
```rust
			InternalEvent::FuzzyFinderChanged(
				idx,
				content,
				target,
			) => {
				match target {
					FuzzyFinderTarget::Branches => self
						.select_branch_popup
						.branch_finder_update(idx)?,
					FuzzyFinderTarget::Files => {
						self.files_tab.file_finder_update(
							&PathBuf::from(content.clone()),
						);
						self.revision_files_popup.file_finder_update(
							&PathBuf::from(content),
						);
					}
                                        // Add an update process here
                                        FuzzyFinderTarget::Something => {
                                                self.something.do_something(idx, content);
                                        }
				}
```
- Add other details, something like command info, hotkeys...

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

### CODE REVIEW

**Comment by UUGTech** [comment]
Hopefully this will make adding a new fuzzy finder a little bit easier.

This PR does not contain anything really new. Do I need to add to CHANGELOG.md?

**Comment by UUGTech** [comment]
Shall I make a new issue to implement something new fuzzy finder? (Is it a log, or...)
Then I can also see if it is really easy or not.

**Comment by extrawurst** [comment]
can you please update this to current master?

**Comment by UUGTech** [comment]
updated

**Pull request merged**
