### PR TITLE
Note AUR package in README

### PR DESCRIPTION
**Pull request by wezm**
I've created [an AUR package](https://aur.archlinux.org/packages/gitui/) for `gitui`. This PR notes it in the README along with the other platforms/distributions.

### CODE REVIEW

**Comment by extrawurst** [comment]
Thank you @wezm for doing this. I have no experience with linux packages, what kind of maintenance do they require ? Whats the process when a new `gitui` release lands?

**Comment by wezm** [comment]
> what kind of maintenance do they require

As package maintainer I mostly just have to update the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gitui) with the new version and checksum when there's a new release.

> Whats the process when a new gitui release lands?

I subscribe to the [Atom feed](https://github.com/extrawurst/gitui/releases.atom) for new releases in my feed reader and have it set up to notify me on my phone of new entries in the feed. So I will notice any new releases and update the AUR package.

I've actually had this in place for a [number of releases](https://aur.archlinux.org/cgit/aur.git/log/?h=gitui) already.

**Comment by extrawurst** [comment]
Pretty cool @wezm! 
Is there a way to automate this?

**Comment by wezm** [comment]
In theory yes but it’s typically done manually so that a human is involved in checking that the new package works, any newly added or removed dependencies are tracked in the PKGBUILD etc.

**Comment by extrawurst** [comment]
I see! wow. Today I learned.
Thanks for doing this❤️

**Comment by extrawurst** [comment]
@wezm one question that came up:
What does this conflict line mean?
```
Conflicts: gitui-git
```

See https://aur.archlinux.org/packages/gitui/

**Comment by wezm** [comment]
Sometimes people create a package for the master version of software in addition to the released version. In that case the convention is to name the package with a -git suffix. Since one of these packages and a package for the release version would likely contain very similar files they can’t coexist since they will try to install files into the Sam paths. The conflicts line says that if someone were to install a hypothetical -git package for gitui it would conflict with this package. In that case pacman will prompt the user and offer to remove this package so the -git one can be installed. Basically it’s just a good practice even though such a package doesn’t, or may never exist. 

Hope that makes sense.

**Pull request merged**
