### PR TITLE
doc: doc about build

### PR DESCRIPTION
**Pull request by alocquet**
This PR is few documentation about how to build the crate.

### CODE REVIEW

**Comment by extrawurst** [comment]
Why do you think you need the nightly toolchain? It works fine for me with stable rust 1.47

**Comment by alocquet** [comment]
I had an error during build. I'll check.

**Comment by alocquet** [comment]
Ok, I was usint rust 1.46 and I had this error message :

```
error: `bitflags::core::num::<impl usize>::saturating_sub` is not yet stable as a const fn
  --> src/ui/mod.rs:16:9
   |
16 |         selection.saturating_sub(height_in_lines) + 1
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by extrawurst** [comment]
Yeah as the readme states: you need the latest stable compiler

**Comment by alocquet** [comment]
Didn't see that there was a 1.47.0 since few days. Sorry. I was trying to help.

**Comment by extrawurst** [comment]
@alocquet don't worry - I appreciate every contribution

**Pull request closed without merging**
