### PR TITLE
Use official Homebrew formula

### PR DESCRIPTION
**Pull request by vladimyr**
GitUI got successfully submitted to the official Homebrew repo. 🎉 
https://formulae.brew.sh/formula/gitui#default

### CODE REVIEW

**Comment by extrawurst** [comment]
@vladimyr this is fantastic! thank you❤️
Did you do this? Currently the CD pipeline automatically updates my personal tap on release - how do we handle the official repo?

**Comment by vladimyr** [comment]
> Did you do this?

Yeah, I'm the one to blame 😁 

> Currently the CD pipeline automatically updates my personal tap on release - how do we handle the official repo?

Well there is this nice little gem that can save you from manually updating it: https://github.com/mislav/bump-homebrew-formula-action I can do a PR if you like, but be warned  that I'm not really experienced with tweaking Github workflows 🙃

**Comment by extrawurst** [comment]
@vladimyr could you checkout the current step: https://github.com/extrawurst/gitui/blob/master/.github/workflows/cd.yml#L74

if you are familiar with the brew command line you could tell me if this should also work if we rewire it to go against the official repo, right?

**Comment by vladimyr** [comment]
Hm, it should you just need to omit personal tap from invocation 🤔 
In the meantime, I already did #138 🙃

**Comment by vladimyr** [comment]
With one change tho, I've used automatically generated tarball inside Homebrew formula (https://github.com/extrawurst/gitui/archive/v0.7.0.tar.gz) instead of mac specific one.

**Comment by extrawurst** [comment]
@vladimyr thanks again, it worked perfectly and is released in `0.8` now: https://github.com/extrawurst/gitui/releases/tag/v0.8.0

**Comment by extrawurst** [comment]
@vladimyr oh no I was too fast there, look the auto update does not touch the test part of the formulae: https://github.com/Homebrew/homebrew-core/pull/57537 😭

**Comment by vladimyr** [comment]
> @vladimyr oh no I was too fast there, look the auto update does not touch the test part of the formulae: https://github.com/Homebrew/homebrew-core/pull/57537 😭

I would say that isn't just a plain update anymore 🤷

**Comment by extrawurst** [comment]
@vladimyr I am lost here. you came up with the original formulae, is the test section a requirement? I can't seem to get it to work: https://github.com/Homebrew/homebrew-core/pull/57537

**Comment by vladimyr** [comment]
Yes, the test section is a requirement and one of the acceptance criteria for the formula to be distributed through homebrew-core tap. However, the test shouldn't get updated on regular releases. The only reason for touching it would be if there are breaking changes introduced with a new release. Give me some time and I'll try to address issues you are seeing there...

**Pull request merged**
