### PR TITLE
feat: help popup display viewing progress

### PR DESCRIPTION
**Pull request by wugeer**
It changes the following:
- help popiup page show viewing progress

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [ ] I tested the overall application
- [x] I added an appropriate item to the changelog

before
[gitui_help_popup_before.webm](https://github.com/user-attachments/assets/628feb94-16b9-41cb-9610-c3a0f307c301)

after
[gitui_help_popup_after.webm](https://github.com/user-attachments/assets/97f736b1-9ac3-4bd0-bfa1-21d2537fb510)

### CODE REVIEW

**Comment by extrawurst** [comment]
Thanks for looking into this. The gitui idiomatic way to show progress on a vertical scroll though is using a scrollbar. so I would suggest we integrate that here too. feel free to join our discord to discuss there things upfront in the future to not waste any effort.

**Comment by wugeer** [comment]
In my personal view, having a percentage-based progress might make it a bit easier to understand. :)
It seems that when scrolling up and down on this page, I didn’t notice a scrollbar on the right side.
image
Also, I’ll create a Discord account a bit later.

**Comment by wugeer** [comment]
@extrawurst  I'll try to add a scrollbar on the right, similar to the one in a browser.:)

**Comment by extrawurst** [comment]
Browser?

Just use the same code we use everywhere else do scroll bars in for example the log tab

**Comment by wugeer** [comment]
Yes, I will try it.
image

**Comment by wugeer** [comment]
@extrawurst Have Done!

**Comment by extrawurst** [comment]
looking good! i wonder why you have different formatting - lets see what the ci says about that

**Comment by wugeer** [comment]
My bad, my local environment was on an unstable version. I switched to the stable version of Rust, and cargo clippy works fine.

**Comment by extrawurst** [comment]
Thanks for your contribution

**Pull request merged**
