### PR TITLE
Continuation of Add search bar at bottom of revlog #506

### PR DESCRIPTION
**Pull request by willir**
Original pull request:
https://github.com/extrawurst/gitui/pull/506

I've fixed the following comments:

1. https://github.com/extrawurst/gitui/pull/506#discussion_r606654156
2. https://github.com/extrawurst/gitui/pull/506#discussion_r606653856
3. https://github.com/extrawurst/gitui/pull/506#discussion_r606654257

Please let me know whether those fixes are enough. 
I'm also not sure whether this way is a good way to continue work of the @WizardOhio24, if not, I'd be glad to do it an alternative way.

### CODE REVIEW

**Comment by willir** [comment]
I hope I fixed the issue. Thanks for pinging me!

**Comment by extrawurst** [comment]
@willir please consider running `make check` locally to be sure the CI will not fail again

**Comment by willir** [comment]
@extrawurst Thanks for suggestion about `make check`. Hope it will pass now.

**Comment by extrawurst** [comment]
> @extrawurst Thanks for suggestion about `make check`. Hope it will pass now.

no problem. could you rebase again?

**Comment by willir** [comment]
I've merged `master` to `find-sha`.

**Comment by willir** [comment]
Hi @heliostatic, I'll try to get back to it this coming weekend.

**Comment by extrawurst** [comment]
@willir still planning to get back to this? putting in draft till then

**Pull request closed without merging**
