### PR TITLE
Update deps, cargo fix, cargo fmt

### PR DESCRIPTION
**Pull request by sigaloid**
```
matt@matt ~/D/G/gitui (master)> cargo update
    Updating crates.io index
    Updating memchr v2.4.0 -> v2.4.1
    Updating object v0.26.0 -> v0.26.1
```
This Pull Request fixes/closes #{N/A}.

It changes the following:
- Updates dependencies (cargo update)
- Converts some characters to fit clippy (not sure how you feel about this, as it makes directly editing these strings difficult. can revert this if necessary)

I followed the checklist:
- [N/A] I added unittests
- [X] I ran `make check` without errors
- [X] I tested the overall application
- [N/A] I added an appropriate item to the changelog

### CODE REVIEW

**Comment by extrawurst** [comment]
@sigaloid thanks for your interest in contributing. 
those two changes are not belonging into the same PR though. I don't see why the cargo update would be needed for the other changes.
regarding the unicode reformatting. I am wondering what that has to do with clippy? I never got a warning for this and I don't find it more readable, quiet the opposit.

**Comment by sigaloid** [comment]
It does indeed make it less readable, I agree. Run cargo clippy and cargo +nightly clippy, I'm fairly certain that triggers the warns.

**Comment by extrawurst** [comment]
Both stable and nightly pipelines are run in the CI and do not trigger any warnings, see here: https://github.com/extrawurst/gitui/runs/3386487942?check_suite_focus=true

**Comment by extrawurst** [comment]
@sigaloid can't reproduce the warnings you see, this PR can be closed

**Pull request closed without merging**
