### PR TITLE
WIP: Refactor external editor

### PR DESCRIPTION
**Pull request by WizardOhio24**
Merge after #312 
Moves `file_to_open` into `external_editor`, so there is only one variable to deal with the external editor in App.

### CODE REVIEW

**Comment by extrawurst** [comment]
@WizardOhio24 sorry that my review delay seem to offend you. closing without any comments seems not constructive. lets keep this open until its reviewed

**Comment by extrawurst** [comment]
converted to draft, it seems to contain changes from other branches

**Comment by extrawurst** [comment]
@WizardOhio24 let me know if you are still interested in getting this merged?

**Comment by WizardOhio24** [comment]
This changes the way external editor works, but it's built on top of the reword PR (because it's kind of pointless without the reword PR).  I can try to split this into a PR only containing only the external editor code, or wait for reword to be merged, then this.  I'd rather wait for reword to be merged, because without that, there isn't much need for this.

**Comment by WizardOhio24** [comment]
So this is waiting for #312

**Comment by WizardOhio24** [comment]
Implemented in #312

**Pull request closed without merging**
