### PR TITLE
Add scrolling to long commit messages

### PR DESCRIPTION
**Pull request by cruessler**
- [x] Manually wrap commit messages
- [x] Add commands for navigation: focus commit message
- [x] Add scrolling to component
- [x] Add tests

### CODE REVIEW

**Comment by extrawurst** [comment]
@cruessler the windows build was broken due to #210 - once you rebase onto current master CI should be fine again

**Comment by cruessler** [comment]
@extrawurst I updated the PR. Scrolling is not yet included, because I first wanted to ask whether the PR goes into the right direction. If so, adding the remaining parts should hopefully not be too difficult.

**Comment by extrawurst** [comment]
@cruessler from a first glance this looks like the way to go 👍

some nitpicks: let's not keep highlighting the top entry in the tree while the commit message is focused. I am also not sure about highlighting a line in the commit message🤔

**Comment by cruessler** [comment]
@extrawurst I have incorporated your feedback, so the PR should be near feature-complete. The only thing missing are a few tests.

**Comment by extrawurst** [comment]
@cruessler really cool, a few tests would be good 👍

**Comment by cruessler** [comment]
@extrawurst I just added a few tests. Let me know if you want more!

**Comment by extrawurst** [comment]
unfortunately it looks not right to me, something is off here:
Screenflick Movie 56

please checkout the amount of up arrows needed until it actually starts scrolling up and how it takes many down-arrow before it starts scrolling down again.

also the clip shows how the entire text is bold instead of only the first line (like it was before).

Can you look into that? You can reproduce it with 1c3295a in the `gitui` repo.

**Comment by cruessler** [comment]
@extrawurst Thanks for the feedback! My first solution was needlessly complicated because it tracked `selection` and `scroll_top` separately. I changed it so that it now only uses `scroll_top` which fixes the issues.

My terminal was not configured to show bold text, so I did not notice the other issue before. I fixed that, too.

**Comment by extrawurst** [comment]
@cruessler really cool! thanks for having pulled through with this! great job!❤️

**Pull request merged**
