### PR TITLE
fix hook panicking

### LINKED ISSUE #393: gitui crashes when trying to run hooks on a vanilla windows machine
If installed on a clean windows install any attempt to run a hook crashes

this is the crash after trying to run 'c' (commit) with pre-commit hooks defined

image

this is because there is no bash on a clean windows system.

### PR DESCRIPTION
**Pull request by extrawurst**
closes #393

### CODE REVIEW

**Comment by extrawurst** [comment]
@pm100 could you gives this a go on a vanilla windows?

**Comment by pm100** [comment]
I have to work out some fancy git footwork :)

**Comment by pm100** [comment]
i am stumped at the moment, this has reached the edge of my git know how. I have to pull from your patch branch into my hook patch branch and resolve conflicts. I suspect I have messed that up cos it still crashes. A total git noob. I will have another go tomorrow. Family calls.

**Comment by extrawurst** [comment]
@pm100 this change makes sense anyway since this is a clear situation where stuff can panic

**Pull request merged**
