### PR TITLE
Set MacOS config directory to ~/.config

### LINKED ISSUE #317: Thoughts on checking `~/.confg/gitui` or `$XDG_CONFIG_HOME/gitui` on mac before defaulting to the existing dir?
Many terminal apps use `~/.config/<app-name>` even on mac. I assume other also have `~/.confg` (or `$XDG_CONFIG_HOME/`) checked into VCS somewhere. It'd be nice to have my gitui config live with all my other terminal app configs :)

Happy to open a PR if this is welcome.

### PR DESCRIPTION
**Pull request by remique**
Hello again :) This fixes #317. I have noticed that no one is working on it, and it seems relatively easy to fix.

Everyone in #317 agreed that Mac config should be kept inside `~/.config/` instead of `~/Library/Application Support/`. 

So now gitui config files will be kept inside:
- MacOS: `~/.config`
- Linux: `~/.config` or `$XDG_CONFIG_HOME`
- Windows: `{FOLDERID_RoamingAppData}`

Did not test it on anything but Mac though.

### CODE REVIEW

**Comment by extrawurst** [comment]
I am going to wait with anything that is non `0.11` milestone related until after the release now. the release will take forever otherwise - any chance u might find one of the `0.11` issues interesting to dig into ?

**Comment by remique** [comment]
Oki, that makes sense. I will look into the `0.11` issues 👍

**Comment by extrawurst** [comment]
@remique don't get me wrong any contribution is appreciated❤️. I will just not merge them before the next release

**Comment by extrawurst** [comment]
@remique that took way longer to come back to than I hoped. 
we need add this to the `CHANGELOG.md` and `KEY_CONFIG.md` before I can merge this

**Comment by shawnohare** [comment]
I can't wait to see this merged :)

**Comment by remique** [comment]
Sorry for the delay guys :)

Btw. is there a cleaner way to `git pull` if `ff-only` is not possible?  As in, I wonder whether I could "merge" these two commits above as one? Or is it okay to leave it like that as once the merge is done, it will be seen as just one commit anyway?

**Comment by extrawurst** [comment]
@remique yeah you can *merge* commits using git rebase (squash)

**Pull request merged**
