### PR TITLE
Show remote branches in log

### LINKED ISSUE #1501: show remote branches In log
only if remote and local are on a different commit

### PR DESCRIPTION
**Pull request by cruessler**
I opened this draft in order to have the PR run on CI. `make check` passes on 1.68.2, but one tests fails on nightly. The PR itself is mostly done, I think. I’ll add more context to this description in the coming days.

This Pull Request closes #1501.

It changes the following:

- Show remote branches in revlog
- Don’t show upstream if commit is local branch head

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [x] I added an appropriate item to the changelog

### CODE REVIEW

**Comment by extrawurst** [comment]
Looks like nightly is just broken on master

**Comment by extrawurst** [comment]
Ping me once you thinks it’s ready 🙏

**Comment by cruessler** [comment]
@extrawurst You can already start testing the main functionality. The two things I still want to add are a changelog entry and a bit more context on possible refactorings.

**Comment by extrawurst** [comment]
lgtm lets move this over the finish line

**Comment by extrawurst** [comment]
Screenshot 2023-04-11 at 15 51 52

small nitpick. we probably can just use the same notation aka `{...}` for remote branches aswell, don't you think? the remotes name kinda implies it already?

**Pull request merged**
