### PR TITLE
Allow multiline commit messgages

### LINKED ISSUE #1171: Create multi-line commit messages
**Is your feature request related to a problem? Please describe.**
Commit with gitui allow only one commit line, without commit description (like is allowed with commit -m command)

**Describe the solution you'd like**
Allow to add a description to the commit: with a new description field, or simply with a multi-line commit

### PR DESCRIPTION
**Pull request by heiskane**
This Pull Request fixes/closes #1171

It changes the following:
- Allow using `enter` to create a newline in commit message box
- Up/Down arrow changes the line the cursor is on
- Keybind to confirm commit message had to be changed to `ctrl + s`
- Works with multibyte/special characters
- Fixes incorrect character count shown in commit message box when multibyte characters are used

I followed the checklist:
- [x] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [x] I added an appropriate item to the changelog

### CODE REVIEW

**Comment by heiskane** [comment]
Just realized I still have to deal with non-ascii characters so I'm changing this to draft.

**Comment by extrawurst** [comment]
@heiskane thanks for tackling this!

**Comment by heiskane** [comment]
> 

No problem although i am having some trouble with non-ascii characters. To clarify the multiline commit messages are in fact working already but the issues with the special characters happen when trying to use up and down arrows to move cursor up/down.

**Comment by extrawurst** [comment]
Yeah the multibyte chars need to work though :)

**Comment by heiskane** [comment]
@extrawurst  I'm still pretty new to contributing on GitHub and not sure if you get pinged when i switch my pull request back to `open` so pinging just to be sure.

**Comment by heiskane** [comment]
@extrawurst Done :+1:

**Comment by extrawurst** [comment]
Screenshot 2022-10-20 at 16 43 43

probably best to squash yourself to figure out what's the problem here

**Comment by heiskane** [comment]
@extrawurst Okay now i think its all correct.

**Comment by heiskane** [comment]
Just realized that the existing `MultiLine` input type does not really mean what i thought it means so this does actually break the input boxes in other places. Not sure how i didnt notice but either way I'm changing this back to draft and ill try to fix it asap :+1:

**Comment by heiskane** [comment]
Sorry for almost messing up there :grimacing:. I thought that the MultiLine type indicated that multiline messages are allowed but that wasn't quite it. I have changed other input boxes correctly to `SingleLine` and increased the singleline input box to make sure that stuff like longer branch names will fit into it (62 characters should be enough to fit right?). Maybe singleline input box could grow in size as needed in the future? I double checked that all input boxes are worked as they should and re-ran tests.

**Comment by extrawurst** [comment]
Screenshot 2022-10-24 at 16 36 27

please squash all your changes together and rebase on top of current master

**Comment by heiskane** [comment]
Squashed

**Comment by extrawurst** [comment]
I tested it again and it does not keep the cursor in view aka it is not scrolling to the line we are editing it only ever keeps the first x lines visible.

**Comment by heiskane** [comment]
> I tested it again and it does not keep the cursor in view aka it is not scrolling to the line we are editing it only ever keeps the first x lines visible.
> 
> let me know in case you cannot reproduce this - you just need to press enter a few times.
> 
> putting it in draft till fixed

I just haven't implemented the scroll yet. I kinda felt like that would be worth another issue but I'll try add it to this PR when I have time 👍

**Comment by extrawurst** [comment]
you are right that it is worth doing a separate smaller PR for. but lets reverse the order and have that separate PR first, because as it is right now the scrolling would already be useful to have in the current state of gitui. can you create a separate PR for that based on current master? this way we do not blow this one up more and still get a nice value added once the first (hopefully smaller) PR is merged. wdyt?

**Comment by heiskane** [comment]
Sure that works for me 👍

**Comment by extrawurst** [comment]
superceded by #1963

**Pull request closed without merging**
