### PR TITLE
Add branch names to rev log

### PR DESCRIPTION
**Pull request by RexTremendae**
Feature suggestion: add local branch names to the revlog. Personally I miss this feature a lot, I use it daily on the command line when working in a team that consists of more people than me :D
feature_branchnames

### CODE REVIEW

**Comment by extrawurst** [comment]
dup of #81, right?

**Comment by RexTremendae** [comment]
@extrawurst I'm not sure what you mean by "accidently share a commit". This PR annotates the commits that are heads of local branches as far as I understand the Rust API. Compare the result with `git log --graph --oneline` on the command line.

**Comment by extrawurst** [comment]
> @extrawurst I'm not sure what you mean by "accidently share a commit". This PR annotates the commits that are heads of local branches as far as I understand the Rust API. Compare the result with `git log --graph --oneline` on the command line.

without #81 you will only annotate the commits that are accidentally *also* on the current branch, since the revlog currently **only** shows commits on the **current** branch. therefore I cannot merge this :(

**Comment by extrawurst** [comment]
marking as draft for now

**Pull request closed without merging**
