### PR TITLE
introduce EventState enum

### LINKED ISSUE #665: introduce EventState enum
`Component::event` returns a `bool` right now marking whether an event was consumed or needs further propagation. this should be a n `enum EventState { Consumed, NotConsumed }`

### PR DESCRIPTION
**Pull request by tisorlawan**
Fix #665

### CODE REVIEW

**Comment by extrawurst** [comment]
@tisorlawan thanks for taking a go at this! could you update the PR so that I can trigger the CI pipeline. for some reason this does not happen by default anymore for first-time-contributors🥺

**Comment by tisorlawan** [comment]
Sorry, what part of it should I update ? I don't quite understand what you mean.

**Comment by extrawurst** [comment]
it currently cannot be merged due to conflicts against master. so it needs being updated to the current master and to resolve the mentioned conflicts.

see what GitHub says:

image

**Comment by extrawurst** [comment]
@tisorlawan thanks! great first time contribution!❤️

**Pull request merged**
