### PR TITLE
Generate rust toolchain file

### PR DESCRIPTION
**Pull request by SergioRibera**
This PR is to add the rust-toolchain file that allows all those who want to contribute or run the project to do it under the same version of Rust

It changes the following:
- Add rust-toolchain file

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

### CODE REVIEW

**Comment by extrawurst** [comment]
Screenshot 2022-10-20 at 19 14 33

I cannot merge this. this overrides the toolchains in CI

**Comment by SergioRibera** [comment]
Hey, i'll done, you can see now the CI can be [override the rust toolchain file](https://github.com/SergioRibera/gitui/actions/runs/3294888668/jobs/5432872782#step:5:30)

> Note: sorry for the other edited files, it's because of an overrun I made

**Comment by extrawurst** [comment]
can you please rebase/squash? I see all kinds of diffs in here that do not belong

**Comment by SergioRibera** [comment]
@extrawurst Done 😃

**Comment by extrawurst** [comment]
Thanks! ❤️

**Pull request merged**
