### PR TITLE
Customize key binds

### LINKED ISSUE #57: different key binding presets
based off of #43 there is still the open issue of how to support different key bindings like `vim`,`emacs` and `nano`. I need input on those, cause I don't use them at all.

The most flexible solution would be having `gitui` dump the default bindings into a config file (on first run) and load it on startup so people can alter it.

My plan is to do it in 2 bigger changes:

### 1. make key bindings dynamic
* refactor the key constants into a type `KeyBindings`
* change all the pattern matching on CT constants for the bindings currently to be done using runtime variables from the `KeyBindings`
* refactor `commands::CommandText` to be dynamic since they reference the keys

### 2. allow changing the bindings
* enable `serde` feature in crossterm to be able to serialise them
* use `ron` to load/save `KeyBindings`

### LINKED ISSUE #109: Ctrl+U and Ctrl+D for page up/down
**Is your feature request related to a problem? Please describe.**
Some keyboards (like mine) don't really have PgUp/PgDown. It would be great to have another keybinding to quickly scroll up and down the Diff pane.

**Describe the solution you'd like**

New keybindings:

 - `Ctrl+U` to scroll up
 - `Ctrl+D` to scroll down

These are the keybindings for `vi`/`vim` so a lot of folks should be familiarized with them.

### PR DESCRIPTION
**Pull request by yanganto**
Hi,
Thanks for providing the awesome git client with amazing terminal UI.
I am also a fan of `neovim` so I make a PR for customizing the key binds with vim style for this project.
This my first PR here,  if there is something lacks consideration, please kindly tell me.
Thanks.

- let user use `ron` config file to customize the key binds
- providing examples
- fix #109 and fix #57

### CODE REVIEW

**Comment by extrawurst** [comment]
@yanganto wow thanks for going after this one, it's probably one of the most awaited feature! I will look at it in more depth later. The only thing that jumps out right away is the usage of a `'static` reference, I wonder if we can clean this up🤔
Will ask in the discord for more people to give it a spin as I know there are people keen on this feature👍

**Comment by extrawurst** [comment]
The windows ci fails due to https://github.com/extrawurst/gitui/issues/235 nothing todo with this PR

**Comment by extrawurst** [comment]
@yanganto two more things: can you make the default key binding simply a default implementation in rust instead of a Schema that's loaded from Ron?
And instead of the lifetimes you can check out `Interieur mutability` in rust, we use it for the `SharedTheme`

**Comment by yanganto** [comment]
- The default key bind config is deleted, it may be misleading.   
- Let keybinds with interieur mutability.

**Comment by cruessler** [comment]
I had a brief look at the PR using the vim-like config, and I very much like it! A few things:

- `focus_left` and `focus_right` seem to be switched.
- I would have expected `page_up` to be `Ctrl+u` and `page_down` to be `Ctrl+d` (the sample config seems to have them switched).
- The hints at the bottom don’t reflect the changed config.

**Comment by yanganto** [comment]
We may open another issue to fix the bottom hints.  How do you think about this? @extrawurst

**Comment by extrawurst** [comment]
@yanganto can u rebase, then the windows ci should work again

**Comment by extrawurst** [comment]
Ok I think this is almost ready to be merged. Great work! I like the way you unified the key-definition and cmd-bar-text so that it automatically matches.

Just small things:
* `KEY_CONFIG.md` now mentions a default-key-config that is not there. I think it makes sense that similarly to the color config on app start we dump the current key config into the config path. That way users can refer to that one and we automatically keep it up to date.
* `→d` for capital `D` seems wrong (see screenshot 1)
* why are many regular colons now a double colons (see screenshot 1 and 3)
* why is the title text `Help` now lowercase? (see screenshot 1)
* previous `Details [enter]` is now `Details IDetails nspect [⏎]` (see screenshot 2)
* when inspecting a commit and focusing on the diff going back `left` does not work anymore (see screenshot 4)
* title key for staged changes seems off (see screenshot 5)

**screenshot 1** master (left) vs. PR (right)`:
key-bindings

**screenshot 2**:
Screenshot 2020-08-25 at 23 56 58

**screenshot 3**:
Screenshot 2020-08-26 at 00 00 43

**screenshot 4**:
Screenshot 2020-08-26 at 00 03 12

**screenshot 5** (the `s` belongs inside the brackets):
Screenshot 2020-08-26 at 00 05 38

**Comment by yanganto** [comment]
@extrawurst Thanks for your review.  Everything is ready.  I hope I can use this on on Archlinux soon :)

**Comment by extrawurst** [comment]
* Arrow left in diff to go back to the file tree still does not work. maybe the diff eats the event so that it does not bubble up to the inspect component?
* →d for capital D is still wrong (see screenshot 1)

**Comment by extrawurst** [comment]
It is merged! Thanks @yanganto for this great effort - many people will be happy with this!❤️

**Comment by yanganto** [comment]
@extrawurst Thanks for review this. <3

**Pull request merged**
