### PR TITLE
add : to signoff trailer

### PR DESCRIPTION
**Pull request by semioticrobotic**
This pull request addresses #2196.

It adds a `:` character to the signoff trailer by default. This character is necessary for complying with the Conventional Commits standard.

I am not a software developer, and unfortunately I do not know how to perform further actions (such as running local tests, etc.). So I will need to request help from someone more knowledgable.

### CODE REVIEW

**Review by matthiasbeyer — APPROVED** [review]
Looks good to me.

**Comment by domtac** [comment]
@semioticrobotic Thanks for adding that. This totally slipped my eye. I originally added it, as I need it for the projects I am working on. Nobody complained so far ;)
But thanks to you it will soon be compliant. Thanks

**Comment by extrawurst** [comment]
@semioticrobotic thanks for tackling this. can you please see the PR checklist and at the very least provide a changelog entry that matches the projects style and at best also a unittest that calls `add_sign_off` ?

**Comment by semioticrobotic** [comment]
Sure thing, @extrawurst. I'm not a software developer, so don't really know how to run unittests or anything of the sort (maybe @domtac can help?). But I can gladly add an item to the changelog.

**Pull request merged**
