### PR TITLE
Windows MSI - add display of file size

### PR DESCRIPTION
**Pull request by pm100**
not tested by me

### CODE REVIEW

**Comment by extrawurst** [comment]
Cool but can you add it to the CI step that I added please? 😉

**Comment by pm100** [comment]
you sure you want to run wix everytime? wix is very slow to build ~ 5 mins

**Comment by extrawurst** [comment]
It looks like it takes ~2.5 min in the CI - Ideen like we can put it in CI until we have one successful release with it and then relax the CI

**Comment by extrawurst** [comment]
@pm100 
do you have an idea why *wix* prints: `WARN: Skipped building the release binary` ?

**Comment by pm100** [comment]
Because we said 'nobuikd' since we just cargo built it. Normally cargo wix would build first

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by extrawurst** [comment]
I see so it uses the binary in `target` instead of building itself?

**Comment by extrawurst** [comment]
@pm100 thank you :)

**Pull request merged**
