### PR TITLE
Allow user to set theme with flag

### PR DESCRIPTION
**Pull request by Th3Whit3Wolf**
### This pull request allows user to set gitui theme by passing a flag (-t,  --theme). Address [Issue 480](https://github.com/extrawurst/gitui/issues/480)

The argument it takes is files a file relative to the app_config directory, meaning if the (linux) user passes `-t example.ron` to gitui then the theme located at `~/.config/gitui/example.ron` will be used. If `~/.config/gitui/example.ron` doesn't exist then `theme.ron` will be used.

This works by setting environment variable `GITUI_THEME` while processing command line arguments and reading it in function get_theme_file.

### CODE REVIEW

**Comment by Th3Whit3Wolf** [comment]
Anything I can do to help get this merged?

**Comment by extrawurst** [comment]
@Th3Whit3Wolf can't we pass the param along differently? it feels wrong to abuse a env variable as a global

**Comment by Th3Whit3Wolf** [comment]
Definitely. I did it that way to have the smallest impact on the codebase. I'll make changes tomorrow.

**Comment by Th3Whit3Wolf** [comment]
I made the changes. `process_cmdline` now return `Result<CliArg>`

```rust
struct CliArgs {
    theme: PathBuf,
}
```
I think this should allow gitui to incorporate more flags down the road with less friction.

theme then gets passed to app which passes it into `Rc::new(Theme::init(theme_path))`

Because `process_cmdline` checks for valid input and returns `theme.ron` if it isn't the get_theme_file  was no longer needed and the save function could be made smaller.

**Comment by Th3Whit3Wolf** [comment]
Anything I can do to help get this merged?

**Comment by extrawurst** [comment]
@Th3Whit3Wolf sorry the code looks fine, can you add some documentation about this into the `THEMES.md` (https://github.com/extrawurst/gitui/blob/master/THEMES.md)?

**Pull request merged**
