### PR TITLE
Show symbol if tag is not yet pushed

### PR DESCRIPTION
**Pull request by cruessler**
This partly addresses #742.

Let me know whether I put the async code in the right place or whether you’d like it moved to a different location!

gitui-tags-remote-indicator

### CODE REVIEW

**Comment by extrawurst** [comment]
Screenflick Movie 29

this does not seem to work quiet yet I am afraid. if I tag a commit and open the tags popup it does not show the new symbol

**Comment by extrawurst** [comment]
> @extrawurst Is this possibly related to authentication being necessary? To test this hypothesis, I updated the PR to call `extract_username_password` and pass the result to `tags_missing_remote` (previously, `None` was passed instead). Can you try whether this has an effect on your machine?

nope that did not fix it. I suspect its related to the fact that you only ever update the `missing_remote_tags` once and then never again

**Comment by cruessler** [comment]
You’re right, spawning the async job inside `if self.missing_remote_tags.is_none()` was not thought through. I removed the conditional and put the call to `spawn` inside `open`, so now the missing tags are refreshed every time the popup is opened.

**Comment by extrawurst** [comment]
works great now! 👍

**Pull request merged**
