### PR TITLE
Better scrolling

### LINKED ISSUE #52: better scrolling in diff/log
now that the diff and log component know their render height, we can make scrolling/selecting more natural by only scrolling once the selection would leave the view instead of always centering the view over the selection.

### PR DESCRIPTION
**Pull request by Stoope**
Fixes #52

### CODE REVIEW

**Comment by extrawurst** [comment]
Hey @Stoope thanks for your contribution! 

But I think I messed up in my explanation in the ticket. What I meant was that when the selection for example would leave the view on the bottom (of log or diff) the view should scroll down one line to keep it in view. similar to the behaviour people know from tools like `less` and `vim`. Do you know what I mean?

**Comment by Stoope** [comment]
Yup, I get it

**Comment by akshay1992kalbhor** [comment]
Hey @extrawurst, what about scrolling up? In vim for example, the cursor has to reach the top of the screen for the view to scroll up. So if your cursor is at the very bottom of the screen (maybe you are scrolling down), you cannot scroll up until the cursor moves all the way up to the upper edge of the screen. Is this what you had in mind?

**Comment by akshay1992kalbhor** [comment]
@extrawurst Well scrolling down is pretty easy, but scrolling up seems complicated to me.

**Comment by Stoope** [comment]
I'm going to implement some stuct for handling scroll. It will store some addition data about previous scrolling to handle up scroll case. Does it make sense?

**Comment by extrawurst** [comment]
I just added an example of this new behaviour for the log view (https://github.com/extrawurst/gitui/commit/dd49d68eab25248c495ada2ad7577380cbf38484)

I don't see the need for any data structures. please feel free to use the new `calc_scroll_top` for the other scrollable lists aswell.

Screenflick Movie 17

**Comment by extrawurst** [comment]
#52 was closed with 112b5c888cd6bb3f8352f21474f5907bb405b749

**Pull request closed without merging**
