### PR TITLE
fix cursor lost at end of line

### PR DESCRIPTION
**Pull request by pm100**

### CODE REVIEW

**Comment by extrawurst** [comment]
image

> This looks slightly odd

I guess these double bars is what you meant?

**Comment by pm100** [comment]
on my system it doesnt look that bad (different fonts I guess) I will change it so that the trailing space is not underlined. Give me a sec

**Comment by extrawurst** [comment]
now testing this I realised we have a bigger issue:

image

new lines are not applied anymore. I suspect this is related to out tui-rs upgrade https://github.com/extrawurst/gitui/pull/289 by @WizardOhio24 - can you check if we can fix this in this PR aswell?

**Comment by WizardOhio24** [comment]
You are most likely correct.  With the TUI update, each new line needs to be in a separate Spans, text in the same Spans is rendered on the same line, and so this code renders all characters on the same line without regard for type of character.  https://github.com/extrawurst/gitui/blob/c4fdbf7aba9b6925b941816e84f4459746cbeb89/src/components/textinput.rs#L134-L138
To fix this you just need to split the lines by '\n', inserting a new spans where each is found(just split, map).  I did this somewhere when I was updating TUI I think.  I believe there was a TUI issue to have text be able to display '\n'(i.e insert a newline) if it wasn't in spans but I'm not sure how it was resolved.

**Comment by pm100** [comment]
> You are most likely correct. With the TUI update, each new line needs to be in a separate Spans, text in the same Spans is rendered on the same line, and so this code renders all characters on the same line without regard for type of character.
> 
> https://github.com/extrawurst/gitui/blob/c4fdbf7aba9b6925b941816e84f4459746cbeb89/src/components/textinput.rs#L134-L138
> 
> 
> To fix this you just need to split the lines by '\n', inserting a new spans where each is found(just split, map). I did this somewhere when I was updating TUI I think. I believe there was a TUI issue to have text be able to display '\n'(i.e insert a newline) if it wasn't in spans but I'm not sure how it was resolved.

The failure happens when there is only one line, it is for sure a tui bug. Look at the screen shots I posted in the tui bug report

**Comment by extrawurst** [comment]
> The failure happens when there is only one line, it is for sure a tui
bug. Look at the screen shots I posted in the tui bug report

ehm no, the screenshot i posted is actually two lines

**Comment by pm100** [comment]
interestingly enough using the external editor on windows (I tried 2 different ones) ends up ignoring the new lines completely.

image

**Comment by extrawurst** [comment]
That’s exactly the problem for which wizard described the cause

**Comment by pm100** [comment]
you want me to roll that fix into this PR?

**Comment by extrawurst** [comment]
we can actually tackle this in another PR first if you like to split it up, but this one has to wait then until we have the general line breaking issue is fixed

**Comment by pm100** [comment]
I am happy to fix it, just wanted to be clear

**Comment by extrawurst** [comment]
@pm100 ok we have a misunderstanding here :( 
What this PR was about is fixing two issues with the displaying of text. For adding this new feature of multiline text editing we should have indeed opened a new PR. Can you Split this in two?

**Comment by pm100** [comment]
So I should make the commit msg read only when you return from ^e? 

BTW: The ^Enter idea came from here , I found it when I was trying to work out how to make ^e work.

https://github.com/extrawurst/gitui/issues/382

**Comment by extrawurst** [comment]
@pm100 can you please check the behaviour of gitui `0.10.1` before the `tui-rs` upgrade in 9316863 because it supported this without being readonly

**Comment by WizardOhio24** [comment]
Don't know if this helps now, but I found the text PR in TUI: https://github.com/fdehau/tui-rs/pull/361, which allows for text to display "\n"(i.e insert a new line).  It might be easier to use what was introduced there, as in allow newline characters, then there doesn't really need to be much change to the way it's currently implemented and should remove the read-only issue.

**Comment by pm100** [comment]
it supported what? The current commit box doesnt support multiple lines, It has no code for up or down arrow, it has no concept of current line. Tell me what you want the behavior to be and I will make it so

**Comment by pm100** [comment]
to be clear - this is not a display issue, thats trivial 2 min fix. The issue is - should the user be allowed to edit a multi line commit message? If 'no' then I will make the commit box read only. If 'yes' then we need this PR.  

Also what should happen if the multi line text has more lines than can be displayed, which lines should be displayed?

I will point out that users will be surprised that they can no longer edit when the return from ^e

**Comment by WizardOhio24** [comment]
So, I think what @extrawurst is saying is that this PR was only to fix the missing cursor at the end of the line.  A multiline editor(A great new feature so the user doesn't have to use an external editor), is a different PR.  So, I think the easiest thing to do is to branch from "Implement full multi-line support in textinput" commit(225b972) and put it in a different PR.  (Correct me if I'm wrong)

I checked out 10.1 and in it you could modify multiple lines but you could only do it by moving right, so you had to keep going right until it "wrapped round" onto a new line.  So I think the way you've implemented it is probably better/easier for the user, i.e using the up/down arrow keys.
I think the problem was that the text input was previously not read only, the user could edit multiple lines by going to the end of the line above and moving right.  The user should be able to edit text as much in GitUI as in an external editor(at a basic level) and it shouldn't be read only.
Hope that helps.

**Comment by pm100** [comment]
i will close this PR.

I will resubmit the original PR for this bug

I will open a separate issue for the multi line issues

**Pull request closed without merging**
