### PR TITLE
Fix scrolling in filetrees

### LINKED ISSUE #295: new folder-folding breaks scrolling
another followup to #288

moving selection and scrolling behaves weird when some folders are collapsed:
Screenflick Movie 74

@WizardOhio24 do you mind also looking into this?

### PR DESCRIPTION
**Pull request by WizardOhio24**
Closes #295 

Fixes scrolling in filetrees

### CODE REVIEW

**Comment by extrawurst** [comment]
@WizardOhio24 can u add a test please?

**Comment by extrawurst** [comment]
@WizardOhio24 this test does not reproduce the problem. removing the *fix* does not fail in this test

**Comment by extrawurst** [comment]
@WizardOhio24 still something off:

Screenflick Movie 75

**Comment by WizardOhio24** [comment]
That should be everything fixed, hopefully :wink:

**Comment by extrawurst** [comment]
@WizardOhio24 any chance to write a particular test accommodating the last commit/fix?

**Comment by extrawurst** [comment]
Thanks @WizardOhio24 ❤️ !

**Pull request merged**
